
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Razorpay Secret
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            RAZORPAY_KEY_SECRET:RAZORPAY_KEY_SECRET
          # This service account has permission to access secrets
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACOOF_8E92D }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          RAZORPAY_KEY_SECRET: ${{ env.RAZORPAY_KEY_SECRET }}
          # This is needed for the build step to access the admin SDK
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACOOF_8E92D }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACOOF_8E92D }}
          channelId: live
          projectId: acoof-8e92d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
