
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1020136778/locations/global/workloadIdentityPools/github-com/providers/github-provider
          service_account: github-action-1020136778@acoof-8e92d.iam.gserviceaccount.com

      - name: Enable required Google Cloud API
        run: gcloud services enable firebaseextensions.googleapis.com

      - name: Get Razorpay Secret
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            RAZORPAY_KEY_SECRET:RAZORPAY_KEY_SECRET

      - name: Get Firebase Service Account Key
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            FIREBASE_SERVICE_ACCOUNT_KEY:FIREBASE_SERVICE_ACCOUNT_KEY
      
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          RAZORPAY_KEY_SECRET: ${{ env.RAZORPAY_KEY_SECRET }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ env.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACOOF_8E92D }}
          channelId: live
          projectId: acoof-8e92d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
